import type { Project } from './types';

export const nextCard: Project = {
  slug: 'next-card',
  index: '01',
  name: 'Next Card',
  tagline: 'Gen Z Credit Card Growth System for China',
  context: 'Mastercard China Advisors Case Competition 2024',
  accent: '--acc-nextcard',
  summary:
    'A strategic pivot for a leading Chinese commercial bank (>30% affluent market share) facing stalled affluent growth. The system re-targets Gen Z (born 1996-2010) with frictionless onboarding, digital-native perks, and viral acquisition, aiming for 300K new cards within a 6-month launch window across the Pearl River Delta.',
  metrics: [
    { label: 'Target population', value: '28.3M' },
    { label: '6-month target', value: '300K cards' },
    { label: 'Target CAC', value: '¥45' },
    { label: 'Activation rate', value: '75%' },
  ],
  chapters: [
    {
      id: 'direction',
      number: '01',
      title: 'Executive Direction & Market Sizing',
      summary: 'Establishing enterprise scope, the strategic pivot, and Tier-1 youth-hub prioritization.',
      images: [
        { file: 'Next_Card_Image_01.png', title: 'Hero Presentation & System Overview', caption: 'Physical metal card renders, mobile interface suite, and Pearl River Delta target map (Shenzhen & Guangzhou).', rationale: 'Establishing enterprise scope connecting market selection, card proposition, and acquisition strategy.', tags: ['Overview'] },
        { file: 'Next_Card_Image_02.png', title: 'Executive Summary — The Answer in 15 Seconds', caption: '28.3M target population, 94% smartphone penetration, 300K 6-month target, ¥45 CAC, 75% activation, 28% referral.', rationale: 'Immediate high-level business clarity for executive stakeholders.', tags: ['Strategy'] },
        { file: 'Next_Card_Image_03.png', title: 'Macro Context & Affluent Stagnation', caption: 'Traditional affluent credit growth decay vs. youth consumption expansion.', rationale: 'Justifying the strategic pivot away from traditional banking demographics.', tags: ['Research'] },
        { file: 'Next_Card_Image_04.png', title: 'Gen Z Demographic & Income Profiling', caption: 'Segmenting 249M Chinese Gen Z adults into students, early-career professionals, and gig creators.', rationale: 'Grounding card feature design in empirical demographic buckets.', tags: ['Research'] },
        { file: 'Next_Card_Image_05.png', title: 'City Selection — Shenzhen vs. Guangzhou', caption: 'Comparative analysis of tech worker density, universities, retail spend, and digital payment adoption.', rationale: 'Prioritizing Tier-1 youth hubs for initial 6-month deployment.', tags: ['Strategy'] },
      ],
    },
    {
      id: 'research',
      number: '02',
      title: 'Research Synthesis & Strategy Mapping',
      images: [
        { file: 'Next_Card_Image_06.png', title: 'Consumer Spending Research Map', caption: 'Discretionary spend across dining, entertainment, travel, and self-improvement.', rationale: 'Identifying high-frequency reward categories.', tags: ['Research'] },
        { file: 'Next_Card_Image_07.png', title: 'Digital Payment Behavior Analysis', caption: 'Mobile payment frequency, app session lengths, mini-program integration patterns.', rationale: 'Designing a mobile-first digital card experience.', tags: ['Research'] },
        { file: 'Next_Card_Image_08.png', title: 'Competitive Benchmarking Matrix', caption: 'Youth credit cards, joint-branded debit products, and BNPL platforms.', rationale: 'Finding whitespace in personalized rewards and fee transparency.', tags: ['Research'] },
        { file: 'Next_Card_Image_09.png', title: 'Underbanking & Credit Access Barriers', caption: 'Approval bottlenecks for young adults without established credit histories.', rationale: 'Designing a step-up credit-limit model based on repayment habits.', tags: ['Research'] },
        { file: 'Next_Card_Image_10.png', title: 'Research Source Map (Source → Insight → Decision)', caption: '8-row evidence matrix connecting census, merchant coverage, and credit distribution to features.', rationale: 'Demonstrating rigorous evidence-driven UX decisions.', tags: ['Method'] },
        { file: 'Next_Card_Image_11.png', title: 'Persona 1 — Alex, Tech Worker (Shenzhen)', caption: 'Needs automated budget tracking, fast cashback on daily rides, instant card controls.', rationale: 'Anchoring functional requirements to realistic workflows.', tags: ['Persona'] },
        { file: 'Next_Card_Image_12.png', title: 'Persona 2 — Chen, University Senior (Guangzhou)', caption: 'Needs low starting limit, no annual fee, campus perks, credit-building tools.', rationale: 'Covering the college-to-career transition.', tags: ['Persona'] },
      ],
    },
    {
      id: 'architecture',
      number: '03',
      title: 'Product Architecture & Card Proposition',
      images: [
        { file: 'Next_Card_Image_13.png', title: 'Value Proposition & Core Features', caption: 'No annual fee, high-yield cashback, local city perks, dynamic credit progression.', rationale: 'A compelling value proposition for digital natives.', tags: ['Product'] },
        { file: 'Next_Card_Image_14.png', title: 'Physical Card Industrial Design', caption: 'Premium brushed-metal finish with neon-orange edge tinting and minimalist chip layout.', rationale: 'A status-symbol product that encourages social sharing.', tags: ['Brand'] },
        { file: 'Next_Card_Image_15.png', title: 'Virtual Card Instant Issuance', caption: 'Real-time tokenized card for immediate Apple Pay / WeChat Pay / Alipay binding.', rationale: 'Eliminating the 3-5 day physical delivery wait.', tags: ['Architecture'] },
        { file: 'Next_Card_Image_16.png', title: 'Information Architecture Map', caption: 'Navigation tree: Account, Benefits, Pay, Missions, Settings.', rationale: 'Shallow navigation depth (max 2 taps to core tasks).', tags: ['IA'] },
        { file: 'Next_Card_Image_17.png', title: 'User Journey Map (Discovery → Loyalty)', caption: 'End-to-end emotional curve across 6 lifecycle stages.', rationale: 'Identifying drop-off risks in onboarding and transaction review.', tags: ['UX'] },
        { file: 'Next_Card_Image_18.png', title: 'Reward Engine Logic & Category Rules', caption: 'Automatic 3% cashback on highest spend category each month.', rationale: 'Removing cognitive friction from rewards programs.', tags: ['Product'] },
        { file: 'Next_Card_Image_19.png', title: 'City Perks Marketplace Ecosystem', caption: 'Hyper-local partnerships (HeyTea, Seesaw, Arabica, Nike, Pop Mart, Trip.com).', rationale: 'Driving daily active opens through localized discounts.', tags: ['Product'] },
        { file: 'Next_Card_Image_20.png', title: 'Referral & Social Growth Engine', caption: 'Dual-sided bonus (500 pts inviter, 200 pts invitee on first transaction).', rationale: 'Lowering CAC via peer recommendation.', tags: ['Growth'] },
        { file: 'Next_Card_Image_21.png', title: 'Responsible Credit Building System', caption: 'Spending alerts, due-date reminders, step-up limit reviews after 3 on-time payments.', rationale: 'Promoting financial wellness for young adults.', tags: ['Product'] },
        { file: 'Next_Card_Image_22.png', title: 'Mobile App Home Dashboard', caption: 'Dark UI: available credit (¥14,520 / ¥20,000), transaction feed, quick pay.', rationale: 'Clean visual hierarchy for daily account management.', tags: ['UI'] },
      ],
    },
    {
      id: 'onboarding',
      number: '04',
      title: 'Frictionless Onboarding & Verification',
      images: [
        { file: 'Next_Card_Image_23.png', title: 'Application Flow (60-Second Approval)', caption: '3-step tracker: Verify Identity → Your Info → Instant Decision.', rationale: 'Minimizing onboarding form fatigue.', tags: ['Onboarding'] },
        { file: 'Next_Card_Image_24.png', title: 'Step 1 — ID OCR & Biometric Liveness', caption: 'Camera scanner for National ID parsing and face verification.', rationale: 'Error-free data entry and automated KYC compliance.', tags: ['KYC'] },
        { file: 'Next_Card_Image_25.png', title: 'Eligibility & Risk Assessment', caption: '18+ filter, status selection, instant approval (¥8,000 limit), manual-review fallback.', rationale: 'Transparent decisioning reducing user anxiety.', tags: ['Risk'] },
        { file: 'Next_Card_Image_26.png', title: 'Step 2 — Income & Employment Input', caption: 'Streamlined forms for allowance, part-time, or early-career salary.', rationale: 'Alternative credit scoring for underbanked youth.', tags: ['Onboarding'] },
        { file: 'Next_Card_Image_27.png', title: 'Step 3 — Instant Virtual Card Activation', caption: 'Celebration UI with instant digital card binding button.', rationale: 'Capitalizing on the emotional peak after approval.', tags: ['UI'] },
        { file: 'Next_Card_Image_28.png', title: 'Physical Card Shipping & Customization', caption: 'Metal colorway selection and delivery tracking.', rationale: 'Tactile brand extension.', tags: ['Product'] },
        { file: 'Next_Card_Image_29.png', title: 'PIN Setup & Security Preferences', caption: 'Touch-optimized PIN keypad and biometric toggle (Face ID / Touch ID).', rationale: 'Secure initial account setup.', tags: ['Security'] },
        { file: 'Next_Card_Image_30.png', title: 'First Transaction Onboarding Tour', caption: 'Guided tooltips for rewards activation and payment QR scanner.', rationale: 'Driving immediate post-approval activation.', tags: ['UX'] },
      ],
    },
    {
      id: 'features',
      number: '05',
      title: 'Core App Features & Interaction Design',
      images: [
        { file: 'Next_Card_Image_31.png', title: 'Benefits & Rewards Hub', caption: 'Points balance (2,850 pts = ¥28.50), earn/redeem toggle, booster banners.', rationale: 'Highlighting tangible monetary value of points.', tags: ['UI'] },
        { file: 'Next_Card_Image_32.png', title: 'Local Perks Directory (Shenzhen)', caption: 'Geo-located merchant cards with exclusive discounts (up to 50% off).', rationale: 'Enhancing local lifestyle relevance.', tags: ['UI'] },
        { file: 'Next_Card_Image_33.png', title: 'Transaction Details & Categorization', caption: 'Merchant logo, category tag, location map, cashback earned, dispute button.', rationale: 'Providing total spend clarity.', tags: ['UI'] },
        { file: 'Next_Card_Image_34.png', title: 'Repayment & Budgeting Control Center', caption: 'Spending-limit sliders, block cash advances, block international transactions.', rationale: 'Empowering user-driven fraud protection and budget control.', tags: ['Product'] },
        { file: 'Next_Card_Image_35.png', title: 'Account Health & Limit Increase Tracker', caption: 'Health gauge ("Good — Keep it up!") and progress to ¥8,000 → ¥12,000.', rationale: 'Gamifying responsible repayment behavior.', tags: ['UX'] },
        { file: 'Next_Card_Image_36.png', title: 'Missions & Achievement System', caption: 'Monthly missions ("Pay 3 times", "Spend over ¥1,000") with point payouts.', rationale: 'Increasing transaction velocity and retention.', tags: ['Growth'] },
        { file: 'Next_Card_Image_37.png', title: 'Push Notification & Alert Suite', caption: 'Lock-screen payment confirmations, points earned, due-date reminders.', rationale: 'Multi-channel engagement strategy.', tags: ['Engagement'] },
        { file: 'Next_Card_Image_38.png', title: 'Customer Support & Self-Service', caption: 'In-app chat, instant card lock, automated FAQ assistant.', rationale: 'Reducing call-center support overhead.', tags: ['Service'] },
      ],
    },
    {
      id: 'campaign',
      number: '06',
      title: 'Marketing Campaign & System Specs',
      images: [
        { file: 'Next_Card_Image_40.png', title: 'Component System & Design Tokens', caption: 'Buttons, inputs, progress bars, tags, color tokens, type scales, dialogs, toasts.', rationale: 'Scalable design-to-code system foundation.', tags: ['Design System'] },
        { file: 'Next_Card_Image_41.png', title: 'Marketing Campaign Structure (Shenzhen Launch)', caption: 'Campaign landing page, campus ambassador toolkit, social ad creatives.', rationale: 'Addressing Question 3 of the Mastercard case prompt.', tags: ['Marketing'] },
        { file: 'Next_Card_Image_42.png', title: 'Acquisition Funnel Analytics', caption: '3.2M reach → 820K engaged → 360K sign-ups → 270K activated → 300K target.', rationale: 'Proving full-funnel conversion tracking.', tags: ['Analytics'] },
        { file: 'Next_Card_Image_43.png', title: 'Campus & Merchant Co-Marketing', caption: 'In-store QR stands, campus pop-ups, co-branded coffee cups.', rationale: 'Bridging digital acquisition with physical touchpoints.', tags: ['Marketing'] },
        { file: 'Next_Card_Image_44.png', title: 'Influencer & UGC Content Strategy', caption: 'Xiaohongshu / Bilibili templates: unboxing, cashback hacks, city-perk redemptions.', rationale: 'Leveraging peer-to-peer social proof.', tags: ['Marketing'] },
        { file: 'Next_Card_Image_45.png', title: 'Paid Digital Performance Ads', caption: 'Mobile ad banners for WeChat Moments and Douyin feeds.', rationale: 'Paid channel growth engineering.', tags: ['Marketing'] },
        { file: 'Next_Card_Image_46.png', title: 'Retention & Life-Stage Transition', caption: 'Auto-transition seniors into graduate career tiers upon diploma verification.', rationale: 'Maximizing long-term customer lifetime value.', tags: ['Retention'] },
        { file: 'Next_Card_Image_47.png', title: 'Risk Controls & Fraud Detection', caption: 'ML velocity rules for unusual patterns and synthetic identity attempts.', rationale: 'Enterprise risk mitigation.', tags: ['Risk'] },
        { file: 'Next_Card_Image_48.png', title: 'Regulatory Compliance & Data Privacy', caption: 'Alignment with PBOC credit reporting rules and PIPL.', rationale: 'Legal compliance verification.', tags: ['Compliance'] },
        { file: 'Next_Card_Image_49.png', title: 'Engineering & API Architecture', caption: 'Endpoints connecting the app to core banking ledger, credit bureau, payment gateways.', rationale: 'Technical buildability proof.', tags: ['Engineering'] },
        { file: 'Next_Card_Image_50.png', title: 'Project Outcome & Measured Impact', caption: 'Recap: 300K acquisition forecast, ¥45 CAC, alignment with leadership goals.', rationale: 'Summarizing business impact for the final review.', tags: ['Impact'] },
        { file: 'Next_Card_Image_51.png', title: 'Reflection & v2.0 Roadmap', caption: 'Lessons learned, technical debt, v2 features (multi-currency wallet, investment sub-accounts).', rationale: 'A mature engineering mindset.', tags: ['Reflection'] },
      ],
    },
  ],
};
